# Read about factories at https://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :restaurant do
    establishment "MyString"
    ownername "MyString"
    address_one "MyString"
    address_two "MyString"
    city "MyString"
    state "MyString"
    zipcode "MyString"
    email "MyString"
    website "MyString"
    phone "MyString"
    restaurant_type "MyString"
    employees "MyString"
    revenue_type "MyString"
    marketing "MyString"
    marketing_budget_boolean "MyString"
    marketing_budget "MyString"
    social_media_boolean "MyString"
    social_media_types "MyString"
    other_social_media_types "MyString"
    online_ads_boolean "MyString"
    online_ads_types "MyString"
    other_online_ads_types "MyString"
    analytics_boolean "MyString"
    analytics_software "MyString"
    social_ads_boolean "MyString"
    why_social_ads "MyString"
    why_social_ads_other "MyString"
    ad_sites "MyString"
    other_ads_sites "MyString"
  end
end
