development:
  adapter: mysql2
  encoding: utf8
  database: swipely_development
  pool: 5
  username: david
  password: david123
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: swipely_test
  pool: 5
  username: david
  password: david123
  host: 127.0.0.1
  port: 3306

production:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  username: david
  password: david123
